# This ConfigMap defines the datasource configuration for Grafana, pointing to the Prometheus service.
# This configurations must match the service name and port defined in the Prometheus deployment to ensure Grafana can connect to it successfully.

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-svc.monitoring.svc.cluster.local:9090
        isDefault: true
        editable: false