#--------------------------------------------------------------------------------------------------------
# Required metadata for SonarCloud analysis
# This file should be placed in the root directory of your project
# Will allow you to run SonarCloud analysis using SonarScanner or as part of your CI/CD pipeline
#--------------------------------------------------------------------------------------------------------

sonar.projectKey=hyrule-iac_kleva-devops-lab
sonar.organization=hyrule-iac
sonar.host.url=https://sonarcloud.io

sonar.sources=app
sonar.exclusions=**/bin/**,**/obj/**
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml