# This configuration file sets up Grafana with a Prometheus datasource and a custom dashboard for the Kleva application. 
# It consists of three main sections: 
# The datasource configuration, a dashboard provider configuration, and a dashboard JSON definition.

# ========================================
# 1. Datasource configuration: Prometheus
# ========================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1" # HELM sidecart will look for this label to import the datasource automatically
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-svc.monitoring.svc.cluster.local:9090
        access: proxy
        isDefault: true
        editable: false

---
# ======================================================================
# 2. Dashboard Provider Configuration to load dashboards from ConfigMaps
# ======================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  provider.yaml: |
    apiVersion: 1
    providers:
      - name: 'kleva-provider'
        orgId: 1
        folder: 'Kleva'
        type: file
        disableDeletion: false
        editable: true
        allowUiUpdates: true
        updateIntervalSeconds: 10
        foldersFromFilesStructure: true
        options:
          path: /var/lib/grafana/dashboards/kleva

---
# =============================================================================================================
# 3. Dashboard JSON to display Kleva metrics
#    This dashboard will be automatically imported by the sidecar based on the label and provider configuration
# =============================================================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard
  namespace: monitoring
  labels:
    grafana_dashboard: "1" # Sidecar will look for this label to import the dashboard automatically
data:

  #The dashboard JSON defines the layout and queries for the Kleva application metrics.
  #Is composed of three panels, the first two are stat panels showing total requests and uptime, 
  #The third is a timeseries panel showing the request rate over time.
  kleva.json: |
    {
      "title": "Kleva App",
      "uid": "kleva-app",
      "schemaVersion": 38,
      "version": 1,
      "panels": [
        {
          "type": "stat",
          "title": "Total requests",
          "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
          "targets": [
            {
              "expr": "sum(kleva_http_requests_total)",
              "legendFormat": "requests"
            }
          ]
        },
        {
          "type": "stat",
          "title": "Uptime (seconds)",
          "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
          "targets": [
            {
              "expr": "kleva_uptime_seconds",
              "legendFormat": "uptime"
            }
          ]
        },
        {
          "type": "timeseries",
          "title": "Request rate (req/sec)",
          "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
          "targets": [
            {
              "expr": "rate(kleva_http_requests_total[1m])",
              "legendFormat": "{{ endpoint }}"
            }
          ]
        }
      ]
    }