# Creates isolated namespaces to segregate resources accordingly and manage access control. 
# In this setup, we have two namespaces:
# - 'app' for the application workloads
# - 'monitoring' for observability stack (Prometheus + Grafana)

 
apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring