# Service exposes the app pods as a stable network endpoint
# ClusterIP = internal only, NodePort = accessible from outside the cluster

  apiVersion: v1
  kind: Service
  metadata:
    name: kleva-app-svc
    namespace: app
  spec:
    selector:
      #Routes traffic to all pods with this label
      app: kleva-app
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
        # Nodeport let you access the app via minikube ip + this port
        nodePort: 30080
    type: NodePort