name: CI

on:
  push:
    branches: [ "master" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-test-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore app/

      - name: Build
        run: dotnet build app/ --configuration Release --no-restore

      - name: Test
        run: dotnet test app/ --no-build --verbosity normal

      - name: Snyk SCA
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --file=app/kleva-app.csproj --severity-threshold=high

      - name: Check Secret Visibility
        run: |
           if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
            echo "El secreto SONAR_TOKEN está VACÍO"
            exit 1
           else
            echo "El secreto tiene un valor configurado"
           fi

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3.1.0 # Intenta usar esta versión más reciente
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}